[06/Aug/2015 08:30:17] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named openstack_regsite.urls
[06/Aug/2015 08:30:18] ERROR [django.request:256] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named openstack_regsite.urls
[06/Aug/2015 08:31:02] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/urls.py", line 3, in <module>
    import openstack_regsite
ImportError: No module named openstack_regsite
[06/Aug/2015 08:31:02] ERROR [django.request:256] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/urls.py", line 3, in <module>
    import openstack_regsite
ImportError: No module named openstack_regsite
[06/Aug/2015 08:35:35] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/urls.py", line 3, in <module>
    import openstack_regsite
ImportError: No module named openstack_regsite
[06/Aug/2015 08:35:35] ERROR [django.request:256] Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 108, in get_response
    response = middleware_method(request)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/middleware/common.py", line 74, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 647, in is_valid_path
    resolve(path, urlconf)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 522, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/urls.py", line 3, in <module>
    import openstack_regsite
ImportError: No module named openstack_regsite
[06/Aug/2015 08:35:53] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 240, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 106, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 8, in <module>
    from openstack_regsite import utils
ImportError: No module named openstack_regsite
[06/Aug/2015 08:35:53] WARNING [django.request:170] Not Found: /favicon.ico
[06/Aug/2015 08:36:32] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 240, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 106, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 11, in <module>
    import utils
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/utils.py", line 4, in <module>
    from keystoneclient.v3 import client as keystone_client
ImportError: No module named keystoneclient.v3
[06/Aug/2015 08:36:34] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 240, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 106, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 11, in <module>
    import utils
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/utils.py", line 4, in <module>
    from keystoneclient.v3 import client as keystone_client
ImportError: No module named keystoneclient.v3
[06/Aug/2015 08:39:12] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 240, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 106, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 12, in <module>
    import logger
ImportError: No module named logger
[06/Aug/2015 08:40:29] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 368, in resolve
    sub_match = pattern.resolve(new_path)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 240, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 106, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 14, in <module>
    logger = logigng.getLogger('openstack_regsite')
NameError: name 'logigng' is not defined
[06/Aug/2015 08:40:38] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 22, in shib_hook
    logger.log("Name attribute is missing!")
TypeError: log() takes at least 3 arguments (2 given)
[06/Aug/2015 08:41:00] ERROR [openstack_regsite:22] Name attribute is missing!
[06/Aug/2015 08:41:00] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 23, in shib_hook
    raise Exception("Missing name attribute.")
Exception: Missing name attribute.
[06/Aug/2015 08:51:17] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 17, in index
    return render_to_response('regsite/index.html')
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: regsite/index.html
[06/Aug/2015 12:28:33] WARNING [django.request:170] Not Found: /static
[06/Aug/2015 12:32:51] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 24, in index
    return render_to_response('regsite/index.html', attributes)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/shortcuts.py", line 39, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/backends/django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/loaders/base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/loaders/base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/base.py", line 190, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/engine.py", line 261, in compile_string
    return parser.parse()
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/base.py", line 341, in parse
    compiled_result = compile_func(self, token)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/contrib/staticfiles/templatetags/staticfiles.py", line 37, in do_static
    return StaticFilesNode.handle_token(parser, token)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/templatetags/static.py", line 126, in handle_token
    path = parser.compile_filter(bits[1])
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/base.py", line 423, in compile_filter
    return FilterExpression(token, self)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/template/base.py", line 639, in __init__
    "from '%s'" % (token[upto:], token))
TemplateSyntaxError: Could not parse the remainder: '-theme.min.css' from 'bootstrap-theme.min.css'
[06/Aug/2015 12:33:14] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:33:14] WARNING [django.request:170] Not Found: /static/bootstrap-theme.min.css
[06/Aug/2015 12:33:18] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:34:59] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:34:59] WARNING [django.request:170] Not Found: /static/bootstrap-theme.min.css
[06/Aug/2015 12:35:03] WARNING [django.request:170] Not Found: /static/bootstrap-theme.min.css
[06/Aug/2015 12:35:12] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:54:39] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:54:39] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:54:40] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:54:40] WARNING [django.request:170] Not Found: /static/bootstrap-theme.min.css
[06/Aug/2015 12:54:41] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:55:05] WARNING [django.request:170] Not Found: /static/
[06/Aug/2015 12:55:06] WARNING [django.request:170] Not Found: /static/
[06/Aug/2015 12:55:07] WARNING [django.request:170] Not Found: /static/
[06/Aug/2015 12:55:07] WARNING [django.request:170] Not Found: /static/
[06/Aug/2015 12:55:08] WARNING [django.request:170] Not Found: /static/
[06/Aug/2015 12:55:08] WARNING [django.request:170] Not Found: /static/
[06/Aug/2015 12:55:15] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:55:33] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:55:41] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:55:41] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:55:42] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:55:42] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:55:55] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:55:55] WARNING [django.request:170] Not Found: /static/bootstrap-theme.min.css
[06/Aug/2015 12:55:56] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:55:56] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:56:00] WARNING [django.request:170] Not Found: /stasic/bootstrap.min.css
[06/Aug/2015 12:56:05] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:56:12] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:56:13] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:56:23] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:56:23] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:56:35] WARNING [django.request:170] Not Found: /static/bootstrap.min.css
[06/Aug/2015 12:59:36] WARNING [django.request:170] Not Found: /favicon.ico
[06/Aug/2015 12:59:36] WARNING [django.request:170] Not Found: /favicon.ico
[06/Aug/2015 13:00:53] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/urls.py", line 9, in <module>
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
NameError: name 'static' is not defined
[06/Aug/2015 13:02:50] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/urls.py", line 9, in <module>
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
NameError: name 'static' is not defined
[06/Aug/2015 13:02:57] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/urls.py", line 9, in <module>
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
NameError: name 'static' is not defined
[06/Aug/2015 13:03:28] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/urls.py", line 9, in <module>
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
NameError: name 'static' is not defined
[06/Aug/2015 13:03:58] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 366, in resolve
    for pattern in self.url_patterns:
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/urls.py", line 10, in <module>
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
NameError: name 'settings' is not defined
[06/Aug/2015 13:04:26] WARNING [django.request:170] Not Found: /bootstrap.min.css
[06/Aug/2015 13:04:26] WARNING [django.request:170] Not Found: /bootstrap-theme.min.css
[06/Aug/2015 13:39:06] WARNING [django.request:170] Not Found: /favicon.ico
[06/Aug/2015 13:52:55] WARNING [django.request:170] Not Found: /shib_hook
[06/Aug/2015 13:53:14] WARNING [django.request:170] Not Found: /shib_hook/
[06/Aug/2015 13:53:16] WARNING [django.request:170] Not Found: /shib_hook
[06/Aug/2015 13:53:25] WARNING [django.request:170] Not Found: /shib_hook
[06/Aug/2015 13:53:47] WARNING [django.request:170] Not Found: /shib_hook
[06/Aug/2015 13:53:59] WARNING [django.request:170] Not Found: /shib_hook
[06/Aug/2015 13:54:03] WARNING [django.request:170] Not Found: /
[06/Aug/2015 13:54:40] ERROR [django.request:256] Internal Server Error: /shib_hook
Traceback (most recent call last):
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/openstack-horizon-shibboleth/openstack_regsite/views.py", line 38, in shib_hook
    return redirect(request.GET['return'])
  File "/opt/openstack-horizon-shibboleth/regsite-venv/lib/python2.7/site-packages/Django-1.8.3-py2.7.egg/django/utils/datastructures.py", line 322, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'return'"
